/*
 * Guest access list for the wedding site.
 * -------------------------------------------------------------------------
 * Two ways a guest can get their card:
 *   1) Type their APPROVED NAME (add names to approvedNames below), OR
 *   2) Type their unique INVITE CODE (generated list below).
 * Anything not on these lists is rejected.
 *
 * To ADD named guests, put full names in the approvedNames array, e.g.:
 *     approvedNames: ["Ada Obi", "Tunde Bello"],
 * (Regenerate codes with: node scripts/generate-guests.js <count>)
 */
window.WEDDING_GUESTS = {
  cardPrefix: "FF26-",

  // Named guests may type their name to receive a card. Add names here:
  approvedNames: [
    // "Full Name Here",
  ],

  // Unique invite codes (one per guest). Give one code to each guest.
  codes: [
    "WED-HNZN",
    "WED-NJJZ",
    "WED-6N7D",
    "WED-MTB2",
    "WED-8Y83",
    "WED-98BD",
    "WED-3FV8",
    "WED-XMR3",
    "WED-UREJ",
    "WED-XJ9E",
    "WED-CPUK",
    "WED-3T96",
    "WED-66U9",
    "WED-TW8U",
    "WED-84BH",
    "WED-46BY",
    "WED-TNAR",
    "WED-G3X7",
    "WED-VA6W",
    "WED-EZXG",
    "WED-MSUA",
    "WED-PZG7",
    "WED-8YD8",
    "WED-44D5",
    "WED-A5HX",
    "WED-RRB9",
    "WED-GXDE",
    "WED-TQYV",
    "WED-9SBZ",
    "WED-V8FY",
    "WED-FWUK",
    "WED-FY6C",
    "WED-NFGG",
    "WED-PQJZ",
    "WED-MJT4",
    "WED-6FTG",
    "WED-SMM7",
    "WED-AHJS",
    "WED-MW7Y",
    "WED-FCXK",
    "WED-FKAP",
    "WED-JMBY",
    "WED-NER2",
    "WED-DXBX",
    "WED-KQH2",
    "WED-A5B9",
    "WED-4BMS",
    "WED-G9MN",
    "WED-B9V3",
    "WED-K4SW",
    "WED-V3TZ",
    "WED-U5WZ",
    "WED-Q2MG",
    "WED-HGZE",
    "WED-2RY7",
    "WED-DRN4",
    "WED-WYB8",
    "WED-2T7V",
    "WED-6CYZ",
    "WED-WRU6",
    "WED-3786",
    "WED-5J8W",
    "WED-7RDW",
    "WED-2C9N",
    "WED-ABXA",
    "WED-6234",
    "WED-7P83",
    "WED-7BQV",
    "WED-G7R5",
    "WED-RTGG",
    "WED-5U9C",
    "WED-V8WD",
    "WED-GZHJ",
    "WED-XNGX",
    "WED-HXZX",
    "WED-AYT9",
    "WED-84RD",
    "WED-MVB9",
    "WED-9ZR7",
    "WED-6YVB",
    "WED-9R4H",
    "WED-CE4B",
    "WED-UGM7",
    "WED-3KF6",
    "WED-EWZD",
    "WED-UU48",
    "WED-WYU2",
    "WED-PVWJ",
    "WED-MY4U",
    "WED-EU4F",
    "WED-KNE6",
    "WED-GCYY",
    "WED-DKP4",
    "WED-V6KX",
    "WED-DRKH",
    "WED-CRDG",
    "WED-XFGE",
    "WED-U665",
    "WED-XQUB",
    "WED-BAKV",
    "WED-XBX5",
    "WED-C6F3",
    "WED-XFVC",
    "WED-VJ27",
    "WED-FB4J",
    "WED-XE2E",
    "WED-5DEQ",
    "WED-T9XH",
    "WED-QVCQ",
    "WED-YRTJ",
    "WED-UJV5",
    "WED-V96F",
    "WED-KEZ9",
    "WED-4NVV",
    "WED-ECJY",
    "WED-BJ7R",
    "WED-TMNW",
    "WED-FH9H",
    "WED-W4GJ",
    "WED-ZTD8",
    "WED-VPQV",
    "WED-XG7G",
    "WED-NQJE",
    "WED-NVSC",
    "WED-MDFH",
    "WED-5M65",
    "WED-EWU7",
    "WED-NXS2",
    "WED-4QWJ",
    "WED-CFDA",
    "WED-ZNMY",
    "WED-EY5K",
    "WED-MR88",
    "WED-5J5C",
    "WED-6HUP",
    "WED-7JJR",
    "WED-A534",
    "WED-7V5C",
    "WED-Q5R6",
    "WED-XVZW",
    "WED-U6KV",
    "WED-2FK7",
    "WED-DUFW",
    "WED-4FYY",
    "WED-WR7V",
    "WED-KFNU",
    "WED-S43B",
    "WED-7JAU",
    "WED-YDTM",
    "WED-NUKX"
  ]
};
